### ISSUE TITLE
Fix zoom confusion for the image resizer dialogs

### ISSUE THREAD

**Issue by illright** [Innopoints/frontend#186]
Perhaps one could also modify the code to support pinching events, if that's a thing. Otherwise just add a zoom slider

**Comment by aabounegm** [comment]
I am not sure what you meant by pinching events, but pinching with my fingers already works great both from my phone and my touch screen laptop.

**Comment by illright** [comment]
I meant the touchpad pinching, for the OSes that support it

**Comment by illright** [comment]
![image](https://user-images.githubusercontent.com/15035286/84512516-ce261a00-acd0-11ea-8655-b53e7db86047.png)
@aabounegm do you think this brings enough clarity to not bother with the zoom slider?

**Comment by aabounegm** [comment]
yeah, seems alright
