### ISSUE TITLE
Avoid showing the resizer popup if the uploaded image already fits the requirements

### ISSUE THREAD

**Issue by illright** [Innopoints/frontend#187]
This link contains a proposed solution: https://stackoverflow.com/a/47786555

**Comment by aabounegm** [comment]
I'm wondering if we should still show the popup for 1) consistency and 2) to enable cropping (zooming in)

**Comment by illright** [comment]
Good point, actually. In that case do we close this?

**Comment by aabounegm** [comment]
Only if you agree that it is in the UX's best interest to keep the feature.
