### ISSUE TITLE
The ticks in the staff hours editor are not prominent enough

### ISSUE THREAD

**Issue by illright** [Innopoints/frontend#208]
One should either make them filled to be a prominent call-to-action, or just resort to autosave. Or both, why not.

Another proposal from the users was to add a label to the button, but I'm afraid the space is tight and a label will not be worth the trouble.

**Comment by aabounegm** [comment]
Or maybe instead of adding a label, change the button itself from a tick to text saying "save".

**Comment by illright** [comment]
I think the first solution is more aesthetically pleasing) also more prominent

**Comment by aabounegm** [comment]
I would say go with just making it filled. Autosave is not 100% guaranteed to work (and may not display any indication that it didn't). Both together can be confusing unless handled well with an indicator saying "saving.." or something, because otherwise the button can appear and disappear quickly

**Comment by illright** [comment]
What I meant is to have the button merely for user reassurance (and to force saving, if it failed), and save all changes automatically under the hood.

**Comment by aabounegm** [comment]
As it seemed like from the last test, the user doesn't need to click for reassurance and assumed it got saved without any interaction with the button. Also, would a "force save" be any different than the auto save?
I don't think combining both is a good idea from both the UX and implementation perspectives. The best option would be either a Google Docs-style "saving the document...", "Document auto-saved" indicator, or a button that clearly indicates that it needs to be pressed for saving. Given that when editing volunteers' hours you need to press "save hours", I think it would be the most consistent and least confusing to opt for the button (perhaps with "💾 save" text) and forget about auto-save.
Also, keep in mind that the only auto-save we have in the website is the local one for projects

**Comment by illright** [comment]
Okay, convincing. But actually the projects autosave is backend-bound, the products one is local
