### ISSUE TITLE
The time picker is unpleasant to use

### ISSUE THREAD

**Issue by illright** [Innopoints/frontend#217]
To fill out both fields you need to click through both fields.

Proposal:
- [ ] Default the picker to 23:59 (seems like the most reasonable deadline time)
- [ ] Switch the focus to the second field when the first field has received a valid value

**Comment by aabounegm** [comment]
The second point would require modification to the TextField component itself since it needs reference to the HTML element to access events (such as `blur`) and methods (such as `focus()`), which seems like too much work to do given that the outcome is just saving one "tab" button press.
