### ISSUE TITLE
Prevent clearing new activity form on pressing "next"

### ISSUE THREAD

**Issue by aabounegm** [Innopoints/frontend#96]
While creating a new project and filling the new activity form, clicking "next" will move to the next step without saving the currently filled data, submitting it, or showing a warning. One of these options should be explored and implemented.
_Suggestion_: In Vue, there is a [`<keep-alive/>`](https://vuejs.org/v2/guide/components-dynamic-async.html#keep-alive-with-Dynamic-Components) component that persists the state of the component and prevents destroying it. I am not sure of the Svelte equivalent.

**Comment by illright** [comment]
Doesn't seem to be a problem any more
